//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_EDMX_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPhone
    {
        public int customerID { get; set; }
        public string phoneNumber { get; set; }
        public string phoneType { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
