//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_EDMX_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class daily_sales
    {
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> day { get; set; }
        public string customer_name { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> sales { get; set; }
    }
}
