//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_EDMX_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery()
        {
            this.DeliveryStaffs = new HashSet<DeliveryStaff>();
        }
    
        public int deliveryID { get; set; }
        public Nullable<System.DateTime> scheduledDelivery { get; set; }
        public string statusDelivery { get; set; }
        public int orderID { get; set; }
    
        public virtual Orderr Orderr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryStaff> DeliveryStaffs { get; set; }
    }
}
