//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_EDMX_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int orderId { get; set; }
        public int foodItemID { get; set; }
        public int quantity { get; set; }
        public decimal discount { get; set; }
        public Nullable<bool> cutlery { get; set; }
        public int packingCost { get; set; }
    
        public virtual FoodItem FoodItem { get; set; }
        public virtual Orderr Orderr { get; set; }
    }
}
