//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_EDMX_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int person_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string full_name { get; set; }
        public string full_name_persisted { get; set; }
        public Nullable<int> age_in_years { get; set; }
    }
}
