//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_EDMX_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public int tax_id { get; set; }
        public string state { get; set; }
        public Nullable<decimal> state_tax_rate { get; set; }
        public Nullable<decimal> avg_local_tax_rate { get; set; }
        public Nullable<decimal> combined_rate { get; set; }
        public Nullable<decimal> max_local_tax_rate { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
