//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        public int cardDetailsID { get; set; }
        public int customerID { get; set; }
        public string cardNumber { get; set; }
        public string cardHolderName { get; set; }
        public byte expiryDate_month { get; set; }
        public short expiryDate_year { get; set; }
        public string CVV { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
