//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TrainingIleanaREntities : DbContext
    {
        public TrainingIleanaREntities()
            : base("name=TrainingIleanaREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<invMiniInventory> invMiniInventories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<CardDetail> CardDetails { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerPhone> CustomerPhones { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryStaff> DeliveryStaffs { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<OrderPayment> OrderPayments { get; set; }
        public virtual DbSet<Orderr> Orderrs { get; set; }
        public virtual DbSet<OrderStatusAudit> OrderStatusAudits { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<brand> brands { get; set; }
        public virtual DbSet<category1> categories1 { get; set; }
        public virtual DbSet<part_prices> part_prices { get; set; }
        public virtual DbSet<part> parts { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<stock> stocks { get; set; }
        public virtual DbSet<address1> addresses1 { get; set; }
        public virtual DbSet<customers1> customers1 { get; set; }
        public virtual DbSet<order_items> order_items { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<tax> taxes { get; set; }
        public virtual DbSet<invMiniInitialInventory> invMiniInitialInventories { get; set; }
        public virtual DbSet<invMiniLocationStore> invMiniLocationStores { get; set; }
        public virtual DbSet<invMiniPallet> invMiniPallets { get; set; }
        public virtual DbSet<invMiniPart> invMiniParts { get; set; }
        public virtual DbSet<invMiniProject> invMiniProjects { get; set; }
        public virtual DbSet<invMiniWarehouse> invMiniWarehouses { get; set; }
        public virtual DbSet<person> persons { get; set; }
        public virtual DbSet<customer1> customers2 { get; set; }
        public virtual DbSet<daily_sales> daily_sales { get; set; }
        public virtual DbSet<product_catalog> product_catalog { get; set; }
        public virtual DbSet<product_info> product_info { get; set; }
        public virtual DbSet<staff_sales> staff_sales { get; set; }
        public virtual DbSet<staff_sales_store> staff_sales_store { get; set; }
        public virtual DbSet<staff_sales_store_years> staff_sales_store_years { get; set; }
    
        public virtual int dynamic_sql_query(string table)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dynamic_sql_query", tableParameter);
        }
    
        public virtual ObjectResult<filter_sort_data_Result> filter_sort_data(string warehouse, string store, string model, string partNumber, Nullable<int> minQuantity, string sortDirection, string sortColumn)
        {
            var warehouseParameter = warehouse != null ?
                new ObjectParameter("Warehouse", warehouse) :
                new ObjectParameter("Warehouse", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("Store", store) :
                new ObjectParameter("Store", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var minQuantityParameter = minQuantity.HasValue ?
                new ObjectParameter("MinQuantity", minQuantity) :
                new ObjectParameter("MinQuantity", typeof(int));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<filter_sort_data_Result>("filter_sort_data", warehouseParameter, storeParameter, modelParameter, partNumberParameter, minQuantityParameter, sortDirectionParameter, sortColumnParameter);
        }
    
        public virtual ObjectResult<findProductByModel_Result> findProductByModel(Nullable<short> model_year, ObjectParameter product_count, ObjectParameter product_price)
        {
            var model_yearParameter = model_year.HasValue ?
                new ObjectParameter("model_year", model_year) :
                new ObjectParameter("model_year", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findProductByModel_Result>("findProductByModel", model_yearParameter, product_count, product_price);
        }
    
        public virtual ObjectResult<findProducts_Result> findProducts(Nullable<decimal> min_list_price, Nullable<decimal> max_list_price, string name)
        {
            var min_list_priceParameter = min_list_price.HasValue ?
                new ObjectParameter("min_list_price", min_list_price) :
                new ObjectParameter("min_list_price", typeof(decimal));
    
            var max_list_priceParameter = max_list_price.HasValue ?
                new ObjectParameter("max_list_price", max_list_price) :
                new ObjectParameter("max_list_price", typeof(decimal));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findProducts_Result>("findProducts", min_list_priceParameter, max_list_priceParameter, nameParameter);
        }
    
        public virtual ObjectResult<findProducts_var2_Result> findProducts_var2(Nullable<decimal> min_list_price, Nullable<decimal> max_list_price, string name)
        {
            var min_list_priceParameter = min_list_price.HasValue ?
                new ObjectParameter("min_list_price", min_list_price) :
                new ObjectParameter("min_list_price", typeof(decimal));
    
            var max_list_priceParameter = max_list_price.HasValue ?
                new ObjectParameter("max_list_price", max_list_price) :
                new ObjectParameter("max_list_price", typeof(decimal));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findProducts_var2_Result>("findProducts_var2", min_list_priceParameter, max_list_priceParameter, nameParameter);
        }
    
        public virtual int genInventory(string warehouse_proc, string store_proc, string model_proc, string partNumber_proc, Nullable<int> yEAR_proc, Nullable<int> minQuantity_proc, string sortColumn_proc, string sortDirection_proc, Nullable<int> pageNumber_proc, Nullable<int> pageSize_proc)
        {
            var warehouse_procParameter = warehouse_proc != null ?
                new ObjectParameter("Warehouse_proc", warehouse_proc) :
                new ObjectParameter("Warehouse_proc", typeof(string));
    
            var store_procParameter = store_proc != null ?
                new ObjectParameter("Store_proc", store_proc) :
                new ObjectParameter("Store_proc", typeof(string));
    
            var model_procParameter = model_proc != null ?
                new ObjectParameter("Model_proc", model_proc) :
                new ObjectParameter("Model_proc", typeof(string));
    
            var partNumber_procParameter = partNumber_proc != null ?
                new ObjectParameter("PartNumber_proc", partNumber_proc) :
                new ObjectParameter("PartNumber_proc", typeof(string));
    
            var yEAR_procParameter = yEAR_proc.HasValue ?
                new ObjectParameter("YEAR_proc", yEAR_proc) :
                new ObjectParameter("YEAR_proc", typeof(int));
    
            var minQuantity_procParameter = minQuantity_proc.HasValue ?
                new ObjectParameter("MinQuantity_proc", minQuantity_proc) :
                new ObjectParameter("MinQuantity_proc", typeof(int));
    
            var sortColumn_procParameter = sortColumn_proc != null ?
                new ObjectParameter("SortColumn_proc", sortColumn_proc) :
                new ObjectParameter("SortColumn_proc", typeof(string));
    
            var sortDirection_procParameter = sortDirection_proc != null ?
                new ObjectParameter("SortDirection_proc", sortDirection_proc) :
                new ObjectParameter("SortDirection_proc", typeof(string));
    
            var pageNumber_procParameter = pageNumber_proc.HasValue ?
                new ObjectParameter("PageNumber_proc", pageNumber_proc) :
                new ObjectParameter("PageNumber_proc", typeof(int));
    
            var pageSize_procParameter = pageSize_proc.HasValue ?
                new ObjectParameter("PageSize_proc", pageSize_proc) :
                new ObjectParameter("PageSize_proc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("genInventory", warehouse_procParameter, store_procParameter, model_procParameter, partNumber_procParameter, yEAR_procParameter, minQuantity_procParameter, sortColumn_procParameter, sortDirection_procParameter, pageNumber_procParameter, pageSize_procParameter);
        }
    
        public virtual int getProductList(Nullable<short> model_year)
        {
            var model_yearParameter = model_year.HasValue ?
                new ObjectParameter("model_year", model_year) :
                new ObjectParameter("model_year", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getProductList", model_yearParameter);
        }
    
        public virtual ObjectResult<GetUserProfile_Result> GetUserProfile(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserProfile_Result>("GetUserProfile", userIdParameter);
        }
    
        public virtual int insertData_Approach2_TVP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertData_Approach2_TVP");
        }
    
        public virtual int query_topN_rows(string table, Nullable<int> topN, string byColumn)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("topN", topN) :
                new ObjectParameter("topN", typeof(int));
    
            var byColumnParameter = byColumn != null ?
                new ObjectParameter("byColumn", byColumn) :
                new ObjectParameter("byColumn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("query_topN_rows", tableParameter, topNParameter, byColumnParameter);
        }
    
        public virtual int RandomInRange_invMiniInventory(Nullable<int> smallestValue, Nullable<int> largestValue, ObjectParameter result)
        {
            var smallestValueParameter = smallestValue.HasValue ?
                new ObjectParameter("smallestValue", smallestValue) :
                new ObjectParameter("smallestValue", typeof(int));
    
            var largestValueParameter = largestValue.HasValue ?
                new ObjectParameter("largestValue", largestValue) :
                new ObjectParameter("largestValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RandomInRange_invMiniInventory", smallestValueParameter, largestValueParameter, result);
        }
    
        public virtual int RandomInRange3(Nullable<int> smallestValue, Nullable<int> largestValue, ObjectParameter result)
        {
            var smallestValueParameter = smallestValue.HasValue ?
                new ObjectParameter("smallestValue", smallestValue) :
                new ObjectParameter("smallestValue", typeof(int));
    
            var largestValueParameter = largestValue.HasValue ?
                new ObjectParameter("largestValue", largestValue) :
                new ObjectParameter("largestValue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RandomInRange3", smallestValueParameter, largestValueParameter, result);
        }
    
        public virtual ObjectResult<spGetMiniInventory_Result> spGetMiniInventory(string warehouse, string store, string model, string partNumber, Nullable<int> minQuantity, string sortColumn, string sortDirection)
        {
            var warehouseParameter = warehouse != null ?
                new ObjectParameter("Warehouse", warehouse) :
                new ObjectParameter("Warehouse", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("Store", store) :
                new ObjectParameter("Store", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var partNumberParameter = partNumber != null ?
                new ObjectParameter("PartNumber", partNumber) :
                new ObjectParameter("PartNumber", typeof(string));
    
            var minQuantityParameter = minQuantity.HasValue ?
                new ObjectParameter("MinQuantity", minQuantity) :
                new ObjectParameter("MinQuantity", typeof(int));
    
            var sortColumnParameter = sortColumn != null ?
                new ObjectParameter("SortColumn", sortColumn) :
                new ObjectParameter("SortColumn", typeof(string));
    
            var sortDirectionParameter = sortDirection != null ?
                new ObjectParameter("SortDirection", sortDirection) :
                new ObjectParameter("SortDirection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetMiniInventory_Result>("spGetMiniInventory", warehouseParameter, storeParameter, modelParameter, partNumberParameter, minQuantityParameter, sortColumnParameter, sortDirectionParameter);
        }
    
        public virtual ObjectResult<uspProductList_Result> uspProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspProductList_Result>("uspProductList");
        }
    }
}
