//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        public int orderPaymentID { get; set; }
        public string paymentMethod { get; set; }
        public string statusPayment { get; set; }
        public decimal totalAmount { get; set; }
        public System.DateTime paymentDate { get; set; }
        public int orderID { get; set; }
    
        public virtual Orderr Orderr { get; set; }
    }
}
