//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusAudit
    {
        public int auditID { get; set; }
        public int orderID { get; set; }
        public string oldStatus { get; set; }
        public string newStatus { get; set; }
        public System.DateTime statusChangedAt { get; set; }
        public string operation { get; set; }
    
        public virtual Orderr Orderr { get; set; }
    }
}
