//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ratingID { get; set; }
        public Nullable<byte> restaurantRating { get; set; }
        public Nullable<byte> deliveryStaffRating { get; set; }
        public int orderID { get; set; }
    
        public virtual Orderr Orderr { get; set; }
    }
}
