//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMXProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_sales_store_years
    {
        public string store_name { get; set; }
        public string address_details { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> amount { get; set; }
    }
}
