//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class invMiniInitialInventory
    {
        public int IdInitialInventory { get; set; }
        public string Warehouse { get; set; }
        public string Project { get; set; }
        public string Store { get; set; }
        public string Location { get; set; }
        public string Made { get; set; }
        public string Model { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> QuantityRandomGenerated { get; set; }
        public Nullable<double> ResultRANDFunction { get; set; }
        public bool isDeleted { get; set; }
    }
}
