//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_catalog
    {
        public string product_name { get; set; }
        public string category_name { get; set; }
        public string brand_name { get; set; }
        public decimal list_price { get; set; }
    }
}
